// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbP7iEGqO3KRbvQUkV4lV9wwoBu0gvZMA',
    appId: '1:761279020165:web:830b47ac50a8a6d655bdec',
    messagingSenderId: '761279020165',
    projectId: 'todo-with-firebase-54970',
    authDomain: 'todo-with-firebase-54970.firebaseapp.com',
    storageBucket: 'todo-with-firebase-54970.firebasestorage.app',
    measurementId: 'G-RDYGRZS5D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIAHWcqrAWj_LGdZMIwwvc5TXYCMAZzzo',
    appId: '1:761279020165:android:40eb171faf51ccc555bdec',
    messagingSenderId: '761279020165',
    projectId: 'todo-with-firebase-54970',
    storageBucket: 'todo-with-firebase-54970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Wh7bxlAWkvRnycExNwHQuTjpqaa5EgA',
    appId: '1:761279020165:ios:af1667773307677755bdec',
    messagingSenderId: '761279020165',
    projectId: 'todo-with-firebase-54970',
    storageBucket: 'todo-with-firebase-54970.firebasestorage.app',
    iosBundleId: 'com.example.todoWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Wh7bxlAWkvRnycExNwHQuTjpqaa5EgA',
    appId: '1:761279020165:ios:af1667773307677755bdec',
    messagingSenderId: '761279020165',
    projectId: 'todo-with-firebase-54970',
    storageBucket: 'todo-with-firebase-54970.firebasestorage.app',
    iosBundleId: 'com.example.todoWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbP7iEGqO3KRbvQUkV4lV9wwoBu0gvZMA',
    appId: '1:761279020165:web:2383e8486095a21055bdec',
    messagingSenderId: '761279020165',
    projectId: 'todo-with-firebase-54970',
    authDomain: 'todo-with-firebase-54970.firebaseapp.com',
    storageBucket: 'todo-with-firebase-54970.firebasestorage.app',
    measurementId: 'G-BPCS9H96DX',
  );
}
